# Generated by Django 3.2.5 on 2021-08-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechicle',
            name='Customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Vechicle', to='customer.customer'),
        ),
    ]
