# Generated by Django 3.2.5 on 2021-08-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=20)),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department', to='Register.registeration')),
            ],
        ),
    ]
