# Generated by Django 3.2.5 on 2021-08-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proffessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clgname', models.CharField(max_length=20)),
                ('deptname', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('ID', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
