# Generated by Django 3.2.5 on 2021-07-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_name', models.CharField(max_length=10)),
                ('dest_price', models.IntegerField()),
                ('dest_desc', models.CharField(max_length=20)),
                ('dest_img', models.ImageField(upload_to='pics')),
                ('dest_offer', models.BooleanField(default=False)),
            ],
        ),
    ]
